version: '3.8'

services:
    gwhtb:
        build: 
          dockerfile: ./docker/Dockerfile
          context: ./
        image: gwhtb:v1
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        mem_limit: 256M
        ports:
          - 4560:4560
        volumes:
          - ./:/usr/src/app
          - /:/opt/ext
        working_dir: /usr/src/app
        shm_size: '256mb'
        env_file:
          - ./.env
        # command: uvicorn runserver:app --port 8000 --host 0.0.0.0 --workers 2
        # restart: unless-stopped
        depends_on:
          - mongodb
            #- mongo-express
        networks:
          - gwhtb_mongo_net

    mongodb:
        image: mongo:4.4.6
        mem_limit: 256M
        env_file:
          - ./.env
        volumes:
          # seeding scripts
          - ./data/configdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
          # named volumes
          - ./data/db:/data/db
          #- ./data/configdb/mongod.conf:/etc/mongod.conf
        networks:
          - gwhtb_mongo_net

#    mongo-express:
#        image: mongo-express
#        ports:
#          - 8081:8081
#        env_file:
#          - ./.express.env
#        # environment:
#        #   ME_CONFIG_MONGODB_SERVER: 'mongodb'
#        #   ME_CONFIG_MONGODB_PORT: '27227'
#        #   ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
#        #   ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
#        #   ME_CONFIG_MONGODB_ADMINPASSWORD: 'admin'
#        depends_on:
#          - mongodb
#        networks:
#          - gwhtb_mongo_net

networks:
  gwhtb_mongo_net:
    driver: bridge
