FROM gwhtb:v1

RUN pip install --no-cache-dir pylint \
							   pylance \
							   black \
							   httpx[socks]

RUN apt-get update && \
	apt-get install -y git curl htop && \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*
